/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.thylex.eveme2.gui.bpValue;

import org.thylex.eveme2.gui.bpValue.BlueprintValuePanel;
import java.awt.BorderLayout;
import java.awt.Component;
import java.awt.Dimension;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Set;
import javax.swing.JPanel;
import javax.swing.JSplitPane;
import org.thylex.eveme2.app.App;
import org.thylex.eveme2.db.sde.IndActivityTypes;
import org.thylex.eveme2.db.sde.IndustryActivityMaterials;
import org.thylex.eveme2.db.sde.InvTypes;

/**
 *
 * @author thyle
 */
public class bpValSplit extends javax.swing.JPanel {

    private App app = null;
    private JPanel left = null;
    private JPanel right = null;
    private JSplitPane split = null;
    /**
     * Creates new form bpValSplit
     */
    public bpValSplit(App appl) {
        app = appl;
        initComponents();
        
        left = new BlueprintValuePanel(app, this);
        left.setMinimumSize(new Dimension(200,100));
        right = new JPanel(); 
        right.setMinimumSize(new Dimension(200,100));
        
        split = new JSplitPane(JSplitPane.HORIZONTAL_SPLIT, left, right);
        split.setContinuousLayout(false);
        split.setOneTouchExpandable(false);
        //split.setResizeWeight(0.3);
        
        this.setLayout(new BorderLayout());
        this.setMinimumSize(new Dimension(400, 200));
        this.add(split);
        
        this.doLayout();
        this.validate();
        
        this.setVisible(true);
    }
    
    public void calcBPValue(InvTypes item) {
        HashMap<String, Set<IndustryActivityMaterials>> sorted = sortItems(item);
        //System.out.println("Sorted size: " + sorted.size());
        
        for (Component c : right.getComponents()) {
            right.remove(c);
        }
        for (String key : sorted.keySet()) {
            //System.out.println(key + ": " + sorted.get(key).size());
            right.add(new MaterialsPanel(key, sorted.get(key)));
        }
        this.validate();
    }
    
    private HashMap<String, Set<IndustryActivityMaterials>> sortItems(InvTypes items) {
        HashMap<String, Set<IndustryActivityMaterials>> result = new HashMap<String, Set<IndustryActivityMaterials>>();
        for (IndustryActivityMaterials mat : app.getSdeWorker().findIndyMaterials(items.getTypeID(), IndActivityTypes.Manufacturing)) {
            String key = mat.getMaterial().getInvGroup().getInvCategory().getCategoryName();
            if (result.containsKey(mat.getMaterial().getInvGroup().getInvCategory().getCategoryName())) {
                Set<IndustryActivityMaterials> temp = result.get(key);
                temp.add(mat);
                result.put(key, temp);
            } else {
                Set<IndustryActivityMaterials> temp;
                temp = new HashSet<>();
                temp.add(mat);
                result.put(key, temp);
            }
        }
        return result;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
