/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.thylex.eveme2.gui.bpValue;

import java.awt.GridLayout;
import java.util.Map;
import java.util.Set;
import javax.swing.JCheckBox;
import javax.swing.JLabel;
import org.thylex.eveme2.io.entities.dyn.TypePrice;
import org.thylex.eveme2.io.entities.sde.IndustryActivityMaterials;

/**
 *
 * @author thyle
 */
public class MaterialsPanel extends javax.swing.JPanel {

    private Set<IndustryActivityMaterials> mats = null;
    /**
     * Creates new form InvTypesPanel
     */
    public MaterialsPanel() {
        initComponents();
    }

    public MaterialsPanel(String title, Set<IndustryActivityMaterials> materials, Map<Integer, TypePrice> prices) {
        mats = materials;

        initComponents();
        // Name, Quantity, Price, Provided
        this.setLayout(new GridLayout((1 + mats.size()), 3));
        this.setBorder(javax.swing.BorderFactory.createTitledBorder(title));
        
        add(new JLabel("Name"));
        add(new JLabel("Quantity"));
        add(new JLabel("Price"));
        add(new JLabel("Provided"));
        
        for (IndustryActivityMaterials mat : mats) {
            this.add(new JLabel(mat.getMaterial().getTypeName() + " "));
            this.add(new JLabel(mat.getQuantity().toString()));
            if (prices.get(mat.getMaterial().getTypeID()) == null) {
                this.add(new JLabel("N/A"));
            } else {
                this.add(new JLabel(prices.get(mat.getMaterial().getTypeID()).getLowSellPrice().toString()));
            }
            this.add(new JCheckBox("", true));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBorder(javax.swing.BorderFactory.createTitledBorder("InvTypesPanel"));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 388, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 278, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
